In [1]:
import numpy as np;

In [2]:
# numpy zeros(X) --> create a numpy array of size X with 0 as values
a = np.zeros(3)
print(a, type(a), type(a[0]), a.shape)

[0. 0. 0.] <class 'numpy.ndarray'> <class 'numpy.float64'> (3,)


In [3]:

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# numpy ones(X) --> create a numpy array of size X with 1 as values
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# numpy empty(X) --> create an empty numpy array that takes a given number of values
a = np.empty(3)
a

array([0., 0., 0.])

In [6]:
# numpy linspace(X, Y, Z) --> create a numpy array of size Z with values ranging from X to Y
a = np.linspace(2, 10, 5)
a

array([ 2.,  4.,  6.,  8., 10.])

In [7]:
# numpy array(myArray) --> create a numpy array from python array or list
myArray = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a =  np.array(myArray)
type(a)
#type(myArray)

numpy.ndarray

In [8]:
a = np.array([3, 5, 7, 3, 2, 9])
a

array([3, 5, 7, 3, 2, 9])

In [9]:
# 2 dimensional numpy array from 2 dimensional numpy list. NB. The array has to have same size
myArray = [[1, 2, 3, 4, 5], [12, 23, 34, 45, 56]] 
a = np.array(myArray)
type(a)
# type(myArray)
# a.shape

numpy.ndarray