In [94]:
import numpy as np;

In [95]:
# Create a numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])

In [96]:
# To apply sinus to every element of my numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.sin(myNumpyArray)

array([[ 0.6569866 ,  0.90929743,  0.14112001, -0.7568025 ,  0.84147098],
       [-0.53657292, -0.8462204 ,  0.52908269,  0.85090352, -0.521551  ]])

In [97]:
# To get sum of all the element of my numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.sum(myNumpyArray)

187

In [98]:
# To get product of all the element of my numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.prod(myNumpyArray)

-322157056

In [99]:
# To get mean of all the element of my numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.mean(myNumpyArray)

18.7

In [100]:
# To get variance of all the element of my numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.var(myNumpyArray)

357.2099999999999

In [101]:
# To get the standard Deviation of all the element of my numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.std(myNumpyArray)

18.9

In [102]:
# To get the minumum value in my numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.min(myNumpyArray)

1

In [103]:
# To get the maximum value in my numpy array
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.max(myNumpyArray)

56

In [104]:
# To get the ArgMin value in my numpy array ---> ArgMin gives you the index value of the minumum value
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.argmin(myNumpyArray)

4

In [105]:
# To get the ArgMax value in my numpy array ---> ---> ArgMax gives you the index value of the maximum value
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
np.argmax(myNumpyArray)

9

#### Using mathematical operation

In [106]:
# To make a copy of your numpy array based on greater than five condition
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
greaterThanFive = myNumpyArray > 5
greaterThanFive

array([[ True, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [107]:
# To make a copy of your numpy array based on less than five condition
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
lessThanFive = myNumpyArray < 5
lessThanFive

array([[False,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [108]:
# To make a copy of your numpy array based on less than five condition
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
filtedBasedonCondition = myNumpyArray[myNumpyArray > 5]
filtedBasedonCondition

array([ 7, 12, 23, 34, 45, 56])

In [109]:
# numpy WHERE method ---> use to replace values based on given condition
myNumpyArray = np.array([[7, 2, 3, 4, 1], [12, 23, 34, 45, 56]])
myMappedNumpyArray = np.where(myNumpyArray < 4, 5, 10)
myMappedNumpyArray

array([[10,  5,  5, 10,  5],
       [10, 10, 10, 10, 10]])

### ADD, MINUS, MULTIPLY, DIVIDE numpy arrays

In [110]:
# Adding two numpy arrays
a1 = np.array([7, 2, 3, 4, 1])
a2 = np.array([12, 23, 34, 45, 56])

a1 + a2

array([19, 25, 37, 49, 57])

In [111]:
# Adding numpy array with a number
a = np.array([7, 2, 3, 4, 1])

a + 30

array([37, 32, 33, 34, 31])

In [112]:
# Multiplying two numpy arrays
a1 = np.array([7, 2, 3, 4, 1])
a2 = np.array([12, 23, 34, 45, 56])

a1 * a2

array([ 84,  46, 102, 180,  56])

In [113]:
# Multiply numpy array with a number
a = np.array([7, 2, 3, 4, 1])

a * 30

array([210,  60,  90, 120,  30])

In [114]:
# Product of two numpy arrays using @. It will multiply each element with element at the same index in the other array then add up all the values.
a1 = np.array([7, 2, 3, 4, 1])
a2 = np.array([12, 23, 34, 45, 56])

a1 @ a2

468

In [118]:
# Transpose a numpy array using T
a = np.array([[1, 2], [3, 4]])
a.T

array([[1, 3],
       [2, 4]])

In [121]:
# Transpose a numpy array using transpose method
a = np.array([[1, 2], [3, 4]])
a.transpose()

array([[1, 3],
       [2, 4]])

In [122]:
# Sorting a numpy array
a = np.array([7, 2, 3, 4, 1])
np.sort(a)

array([1, 2, 3, 4, 7])

In [126]:
a = np.array([[7, 2], [5, 4]])
np.sort(a)

array([[2, 7],
       [4, 5]])