In [7]:
# Importing torch
import torch;

In [32]:
# Creating a tensor variable
v = torch.tensor([1, 2, 3])
print(v)
print(v.dtype)

tensor([1, 2, 3])
torch.int64


In [31]:
# FloatTensor
v = torch.FloatTensor([1, 2, 3])
print(v)
print(v.dtype)


tensor([1., 2., 3.])
torch.float32


In [37]:
# Accessing tensor value at given index or from range of indexes (its the same as you will access value in a python list)
inpair = torch.tensor([1, 3, 5, 7, 9])
print(inpair[0])
print(inpair[2])
print(inpair[2:4])
print(inpair[2:])
print(inpair[:4])
print(inpair[-1])

tensor(1)
tensor(5)
tensor([5, 7])
tensor([5, 7, 9])
tensor([1, 3, 5, 7])
tensor(9)


In [40]:
# Tensor build in methods
pair = torch.tensor([2, 4, 6, 8, 10, 12])

# 1. size() use to get length
print(pair.size())

# 1. view(nRow, nCol) method. Its the same as reshape method in numpy array
print(pair.view(3, 2)) 
print(pair.view(2, -1)) # -1 will authomatically set the number of columns based on the size or length of the tensor array

torch.Size([6])
tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [43]:
# Converting numpy array into tensor
import numpy as np;

npArray = np.array([1, 2, 3, 4, 5, 6])
print(npArray)

tensor_cnv = torch.from_numpy(npArray)
print(tensor_cnv)

[1 2 3 4 5 6]
tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)


In [50]:
# Converting tensor into numpy array
tensor_val = torch.tensor([2, 4, 6, 8, 10, 12])
print(tensor_val)

numpy_cnv = tensor_val.numpy()
print(numpy_cnv)

tensor([ 2,  4,  6,  8, 10, 12])
[ 2  4  6  8 10 12]
