In [22]:
# Importing
import torch;

In [23]:
# Lets start by making a 1D tensor using arange method
one_d = torch.arange(0, 18)
print(one_d)
print(one_d.dim()) 

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])
1


In [24]:
three_d = one_d.view(3, 2, -1)
print(three_d)
print(three_d.dim())

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])
3


In [25]:
# Indexes in 2D or Matrix tensor by passing in the positions
print(three_d[1])
print(three_d[0, 1])
print(three_d[2, 1, 1])

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])
tensor([3, 4, 5])
tensor(16)


In [37]:
# Slicing 3D Tensor
print(three_d[1, 0:2, 0:3])

print(three_d[1, 1, 0:3])
print(three_d[1][1][0:3])

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])
tensor([ 9, 10, 11])
tensor([ 9, 10, 11])
