## Matrix Multiplication

To multiply two matrix A and B, the number of Columns of Matrix A has to be equal to the number of Rows of matrix B

In [4]:
# importing torch
import torch

### Matrix multiplication using matmul torch method

In [28]:
# Example 1
matrixA = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
matrixB = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
print(matrixA)
print(matrixB)
print(torch.matmul(matrixA, matrixB))

tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])
tensor([[ 29, -16],
        [ 38,   6]])


In [29]:
# Example 2
matrixA = torch.tensor([3, 1, 4]).view(1, 3)
matrixB = torch.tensor([4, 3, 2, 5, 6, 8]).view(3, 2)
print(matrixA)
print(matrixB)
print(torch.matmul(matrixA, matrixB))

tensor([[3, 1, 4]])
tensor([[4, 3],
        [2, 5],
        [6, 8]])
tensor([[38, 46]])


### Matrix multiplication using @ symbol

In [30]:
# Example 1
matrixA = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
matrixB = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
print(matrixA)
print(matrixB)
print(matrixA @ matrixB)

tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])
tensor([[ 29, -16],
        [ 38,   6]])


In [31]:
# Example 2
matrixA = torch.tensor([3, 1, 4]).view(1, 3)
matrixB = torch.tensor([4, 3, 2, 5, 6, 8]).view(3, 2)
print(matrixA)
print(matrixB)
print(matrixA @ matrixB)

tensor([[3, 1, 4]])
tensor([[4, 3],
        [2, 5],
        [6, 8]])
tensor([[38, 46]])
