In [2]:
import numpy as np;
import time;

In [1]:
a = np.array([1, 2, 3, 4])

print(a)

[1 2 3 4]


In [46]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
print(a)

[0.55033392 0.80452145 0.68351518 ... 0.89372797 0.23214264 0.89249106]


## Vectorized Vesion

In [47]:
tic = time.time()

# start here

c = np.dot(a, b)

# ends here

toc = time.time()

print(tic)
print(toc)
print("Vectorized Version took " + str(1000 * (toc - tic)) + " ms")
print("C = " + str(c))

1716075952.9097779
1716075952.9128656
Vectorized Version took 3.087759017944336 ms
C = 249907.79974580684


## None Vectorized Version

In [37]:
tic = time.time()

# start here
c = 0
for i in range(len(a)):
    c += a[i]*b[i]
# ends here

toc = time.time()

print(tic)
print(toc)
print("Vectorized Version took " + str(1000 * (toc - tic)) + " ms")
print("C = " + str(c))

1716067929.7344468
1716067929.9801106
Vectorized Version took 245.66388130187988 ms
C = 249976.65489962598


In [48]:
a=np.random.randn(2,3)
b=np.random.randn(2,1)
c=a+b
c.shape

(2, 3)

In [60]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
c.shape

(3, 3)

In [8]:
a = np.array([[2,1],[1,3]])
c = np.dot(a,a)
print(c)

[[ 5  5]
 [ 5 10]]


In [61]:
a= np.random.randn(3,3)
b= np.random.randn(3,3)
c = a**2 + b.T**2
a.shape

(3, 3)

In [57]:
x = np.array([[[1], [2]], [[3], [4]]])
x.shape

(2, 2, 1)

In [12]:
a= np.random.randn(4,3)
b= np.random.randn(4,1)

c = a + b
c


array([[ 1.392411  , -0.2011453 ,  0.04545916],
       [ 1.84376018,  2.37348568,  0.19152552],
       [-1.36605937, -2.05084181, -1.5537767 ],
       [-2.44092544, -0.57087484, -1.18834381]])

In [5]:
a= np.random.randn(3,3)
b= np.random.randn(2,1)
c = a + b
a.shape

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [68]:
x = np.random.randn(8, 1)
x.reshape(2, 2, 2)


array([[[-1.43026474, -0.04312762],
        [-0.63590548, -0.13010073]],

       [[-0.49504989,  1.10279202],
        [-0.20472335,  0.13021121]]])

In [74]:
a= np.random.randn(3,4)
b= np.random.randn(4,1)
c = a.T + b
# for i in range(3):

#  for j in range(4):

#     c[i][j] = a[i][j] + b[j]
c

array([[-0.00857439,  0.68037799,  1.2302979 ],
       [-1.40990103, -0.46290847, -1.00832734],
       [ 2.62157014,  3.37622065,  2.36022218],
       [ 0.71495718,  1.73068449, -0.08973732]])

In [13]:
a = np.array([[1, 1], [1, -1]])
b=np.array([[2],[3]])
c=a+b
c

array([[3, 3],
       [4, 2]])