In [1]:
import numpy as np

In [3]:
A = np.array([[56, 0, 4.4, 68], [1.2, 104, 52, 8], [1.8, 135, 99, 0.9]]) # This is a 3 * 4 matrix
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis=0) # axis=0 to sum vertically and axis=1 to sum horizontally. Also cal here is a 1 * 4 vector
print(cal)

[ 59.  239.  155.4  76.9]


## Broadcasting (Dividing 3 * 4 matrix with a 1 * 4 vector)

In [5]:
percentage = 100 * (A/cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [6]:
# no need of .reshape since cal is already already a 1 * 4 vector
percentage = 100 * (A/cal)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


: 